PRODUCT_VERSION_MAJOR = 2
PRODUCT_VERSION_MINOR = 0

CURRENT_DEVICE=$(shell echo "$(TARGET_PRODUCT)" | cut -d'_' -f 2,3)

FAOSP_BUILDTYPE ?= UNOFFICIAL

FAOSP_VERSION := FAOSP-v$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)-$(CURRENT_DEVICE)-$(FAOSP_BUILDTYPE)-$(shell date -u +%Y%m%d-%H%M)

# Display version
FAOSP_DISPLAY_VERSION := v$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR)

# Fork AOSP version properties
PRODUCT_SYSTEM_PROPERTIES += \
    ro.faosp.version=$(FAOSP_VERSION) \
    ro.faosp.display.version=$(FAOSP_DISPLAY_VERSION) \
    ro.faosp.build.version=$(PRODUCT_VERSION_MAJOR).$(PRODUCT_VERSION_MINOR) \
    ro.faosp.releasetype=$(FAOSP_BUILDTYPE)
